---
name: Run Statsig Server Build

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch: {}

jobs:
  build-statsig-server:
    name: Build swift-statsig-server
    runs-on: ubuntu-latest
    container:
      image: swift:6.2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Check changed files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            src:
              - 'iOS/swift-statsig-server/**'

      - name: Install native dependencies
        if: steps.changes.outputs.src == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            pkg-config \
            libssl-dev \
            libboost-all-dev

      - name: Build swift-statsig-server
        if: steps.changes.outputs.src == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          cd iOS/swift-statsig-server
          swift build
